### PR TITLE
Whoops... :)

### PR DESCRIPTION
**Pull request by josephlimb**
Add callbacks from https://github.com/dbushell/Nestable/pull/143

### CODE REVIEW

**Comment by josephlimb** [comment]
I accidentally issued a pull request the wrong way. :) Sorry to bug you :)

**Comment by BeFiveINFO** [comment]
Don't worry :)

**Comment by bigfoot90** [comment]
Why you have removed usage examples?

**Comment by BeFiveINFO** [comment]
I think that the usage example is still there (see readme in the repo)

**Pull request closed without merging**
